<?php

namespace Dgtlss\Warden\Services\OutputFormatters;

use Dgtlss\Warden\ValueObjects\Finding;

/**
 * HTML report generator for security audit findings.
 */
class HtmlFormatter
{
    /**
     * Format findings as an HTML report.
     *
     * @param array<int, Finding> $findings
     */
    public function format(array $findings): string
    {
        $summary = $this->generateSummary($findings);
        $findingsBySource = $this->groupFindingsBySource($findings);
        $severityBreakdown = $this->generateSeverityBreakdown($findings);

        $html = <<<HTML
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Warden Security Audit Report</title>
    <style>
        {$this->getStyles()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>🛡️ Warden Security Audit Report</h1>
            <p class="timestamp">Generated: {$this->getTimestamp()}</p>
        </header>

        {$summary}
        {$severityBreakdown}
        {$this->generateFindingsTable($findingsBySource)}

        <footer>
            <p>Generated by <a href="https://github.com/dgtlss/warden">Warden v1.4.1</a></p>
        </footer>
    </div>
</body>
</html>
HTML;

        return $html;
    }

    /**
     * Generate executive summary section.
     *
     * @param array<int, Finding> $findings
     */
    protected function generateSummary(array $findings): string
    {
        $total = count($findings);
        $critical = $this->countBySeverity($findings, 'critical');
        $high = $this->countBySeverity($findings, 'high');
        $medium = $this->countBySeverity($findings, 'medium') + $this->countBySeverity($findings, 'moderate');
        $low = $this->countBySeverity($findings, 'low');

        $status = $critical > 0 || $high > 0 ? 'critical' : ($medium > 0 ? 'warning' : 'success');

        return <<<HTML
<section class="summary">
    <h2>Executive Summary</h2>
    <div class="summary-grid">
        <div class="summary-card {$status}">
            <div class="summary-number">{$total}</div>
            <div class="summary-label">Total Findings</div>
        </div>
        <div class="summary-card critical">
            <div class="summary-number">{$critical}</div>
            <div class="summary-label">Critical</div>
        </div>
        <div class="summary-card high">
            <div class="summary-number">{$high}</div>
            <div class="summary-label">High</div>
        </div>
        <div class="summary-card medium">
            <div class="summary-number">{$medium}</div>
            <div class="summary-label">Medium</div>
        </div>
        <div class="summary-card low">
            <div class="summary-number">{$low}</div>
            <div class="summary-label">Low</div>
        </div>
    </div>
</section>
HTML;
    }

    /**
     * Generate severity breakdown section.
     *
     * @param array<int, Finding> $findings
     */
    protected function generateSeverityBreakdown(array $findings): string
    {
        if (empty($findings)) {
            return '<section class="no-findings"><h2>✅ No Security Issues Found</h2><p>Your application passed all security audits.</p></section>';
        }

        return '';
    }

    /**
     * Generate findings table grouped by source.
     *
     * @param array<string, array<int, Finding>> $findingsBySource
     */
    protected function generateFindingsTable(array $findingsBySource): string
    {
        $html = '<section class="findings">';

        foreach ($findingsBySource as $source => $findings) {
            $html .= "<h2>📋 {$source}</h2>";
            $html .= '<table class="findings-table">';
            $html .= '<thead><tr><th>Severity</th><th>Package</th><th>Issue</th><th>Details</th><th>Remediation</th></tr></thead>';
            $html .= '<tbody>';

            foreach ($findings as $finding) {
                $severityClass = strtolower($finding->severity->value);
                $severityLabel = ucfirst($finding->severity->value);

                $html .= '<tr>';
                $html .= "<td><span class=\"badge {$severityClass}\">{$severityLabel}</span></td>";
                $html .= "<td>" . htmlspecialchars($finding->package) . "</td>";
                $html .= "<td>" . htmlspecialchars($finding->title) . "</td>";
                $html .= "<td>" . $this->formatDetails($finding) . "</td>";
                $html .= "<td>" . $this->formatRemediation($finding) . "</td>";
                $html .= '</tr>';
            }

            $html .= '</tbody></table>';
        }

        $html .= '</section>';

        return $html;
    }

    /**
     * Format finding details.
     */
    protected function formatDetails(Finding $finding): string
    {
        $details = '';

        if ($finding->error) {
            $details .= htmlspecialchars($finding->error);
        }

        if ($finding->cve) {
            $details .= "<br><strong>CVE:</strong> " . htmlspecialchars($finding->cve);
        }

        if ($finding->affectedVersions) {
            $details .= "<br><strong>Affected:</strong> " . htmlspecialchars($finding->affectedVersions);
        }

        return $details ?: '-';
    }

    /**
     * Format remediation suggestions.
     */
    protected function formatRemediation(Finding $finding): string
    {
        if (!$finding->hasRemediation() || $finding->remediation === null) {
            return '<span class="no-remediation">-</span>';
        }

        $remediation = $finding->remediation;
        $html = '<div class="remediation">';

        $priorityClass = match ($remediation->priority) {
            'immediate' => 'priority-immediate',
            'high' => 'priority-high',
            'medium' => 'priority-medium',
            default => 'priority-low',
        };

        $html .= '<span class="priority-badge ' . $priorityClass . '">' . ucfirst($remediation->priority) . '</span>';
        $html .= '<p class="remediation-desc">' . htmlspecialchars($remediation->description) . '</p>';

        if ($remediation->hasCommands()) {
            $html .= '<div class="remediation-commands"><strong>Commands:</strong><ul>';
            foreach ($remediation->commands as $command) {
                $html .= '<li><code>' . htmlspecialchars($command) . '</code></li>';
            }
            $html .= '</ul></div>';
        }

        if ($remediation->hasManualSteps()) {
            $html .= '<div class="remediation-steps"><strong>Manual Steps:</strong><ul>';
            foreach ($remediation->manualSteps as $step) {
                $html .= '<li>' . htmlspecialchars($step) . '</li>';
            }
            $html .= '</ul></div>';
        }

        if ($remediation->hasLinks()) {
            $html .= '<div class="remediation-links"><strong>References:</strong><ul>';
            foreach ($remediation->links as $link) {
                $escapedLink = htmlspecialchars($link);
                $html .= '<li><a href="' . $escapedLink . '" target="_blank" rel="noopener">' . $escapedLink . '</a></li>';
            }
            $html .= '</ul></div>';
        }

        $html .= '</div>';

        return $html;
    }

    /**
     * Group findings by source.
     *
     * @param array<int, Finding> $findings
     * @return array<string, array<int, Finding>>
     */
    protected function groupFindingsBySource(array $findings): array
    {
        $grouped = [];

        foreach ($findings as $finding) {
            $source = $finding->source;
            if (!isset($grouped[$source])) {
                $grouped[$source] = [];
            }
            $grouped[$source][] = $finding;
        }

        return $grouped;
    }

    /**
     * Count findings by severity.
     *
     * @param array<int, Finding> $findings
     */
    protected function countBySeverity(array $findings, string $severity): int
    {
        return count(array_filter($findings, fn($f) => strtolower($f->severity->value) === $severity));
    }

    protected function getTimestamp(): string
    {
        return date('Y-m-d H:i:s');
    }

    protected function getStyles(): string
    {
        return <<<CSS
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif; background: #f5f7fa; color: #2d3748; line-height: 1.6; }
.container { max-width: 1400px; margin: 0 auto; padding: 2rem; }
header { text-align: center; margin-bottom: 3rem; }
header h1 { font-size: 2.5rem; color: #1a202c; margin-bottom: 0.5rem; }
.timestamp { color: #718096; font-size: 0.9rem; }
section { background: white; border-radius: 8px; padding: 2rem; margin-bottom: 2rem; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
h2 { color: #2d3748; margin-bottom: 1.5rem; font-size: 1.5rem; }
.summary-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 1rem; }
.summary-card { padding: 1.5rem; border-radius: 6px; text-align: center; border: 2px solid; }
.summary-number { font-size: 2.5rem; font-weight: bold; margin-bottom: 0.5rem; }
.summary-label { font-size: 0.9rem; text-transform: uppercase; letter-spacing: 0.05em; opacity: 0.8; }
.summary-card.success { background: #f0fdf4; border-color: #86efac; color: #166534; }
.summary-card.warning { background: #fef3c7; border-color: #fcd34d; color: #92400e; }
.summary-card.critical { background: #fee2e2; border-color: #fca5a5; color: #991b1b; }
.summary-card.high { background: #ffedd5; border-color: #fdba74; color: #9a3412; }
.summary-card.medium { background: #fef3c7; border-color: #fcd34d; color: #92400e; }
.summary-card.low { background: #dbeafe; border-color: #93c5fd; color: #1e40af; }
.findings-table { width: 100%; border-collapse: collapse; margin-top: 1rem; }
.findings-table th { background: #f9fafb; padding: 0.75rem; text-align: left; font-weight: 600; border-bottom: 2px solid #e5e7eb; }
.findings-table td { padding: 0.75rem; border-bottom: 1px solid #e5e7eb; vertical-align: top; }
.findings-table tr:hover { background: #f9fafb; }
.badge { display: inline-block; padding: 0.25rem 0.75rem; border-radius: 9999px; font-size: 0.75rem; font-weight: 600; text-transform: uppercase; }
.badge.critical { background: #fecaca; color: #991b1b; }
.badge.high { background: #fed7aa; color: #9a3412; }
.badge.medium, .badge.moderate { background: #fef08a; color: #92400e; }
.badge.low { background: #bfdbfe; color: #1e40af; }
.no-findings { text-align: center; padding: 3rem; color: #059669; }
.no-findings h2 { color: #059669; }
footer { text-align: center; padding: 2rem; color: #718096; }
footer a { color: #3182ce; text-decoration: none; }
footer a:hover { text-decoration: underline; }
.remediation { font-size: 0.875rem; max-width: 400px; }
.remediation-desc { margin: 0.5rem 0; color: #4a5568; }
.remediation-commands, .remediation-steps, .remediation-links { margin-top: 0.75rem; }
.remediation-commands ul, .remediation-steps ul, .remediation-links ul { margin-left: 1rem; margin-top: 0.25rem; }
.remediation-commands li, .remediation-steps li, .remediation-links li { margin-bottom: 0.25rem; }
.remediation code { background: #f1f5f9; padding: 0.125rem 0.375rem; border-radius: 4px; font-family: 'SF Mono', Monaco, 'Courier New', monospace; font-size: 0.8rem; color: #1e40af; word-break: break-all; }
.remediation a { color: #3182ce; text-decoration: none; word-break: break-all; }
.remediation a:hover { text-decoration: underline; }
.priority-badge { display: inline-block; padding: 0.125rem 0.5rem; border-radius: 4px; font-size: 0.7rem; font-weight: 600; text-transform: uppercase; margin-bottom: 0.25rem; }
.priority-immediate { background: #fecaca; color: #991b1b; }
.priority-high { background: #fed7aa; color: #9a3412; }
.priority-medium { background: #fef08a; color: #92400e; }
.priority-low { background: #bfdbfe; color: #1e40af; }
.no-remediation { color: #a0aec0; }
CSS;
    }
}
