<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Warden Audit Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f5f5f5;
            margin: 0;
            padding: 40px 20px;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            background-color: #ffffff;
            border-radius: 8px;
            padding: 30px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .logo {
            text-align: center;
            margin-bottom: 20px;
        }
        .logo img {
            max-width: 100px;
            border-radius: 360px;
            height: 100px;
            width: 100px;
        }
        .title {
            font-size: 24px;
            font-weight: bold;
            color: #333333;
            text-align: center;
            margin-bottom: 30px;
        }
        .report-content {
            color: #444444;
            line-height: 1.6;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #eeeeee;
        }
        th {
            background-color: #f8f8f8;
            font-weight: 600;
        }
        footer{
            display: flex;
            justify-content: center;
            align-items: center;
            margin-top: 30px;
            flex-direction: column;
            gap: 2px;
            font-size: 12px;
        }
        footer a {
            color: #333333;
            text-decoration: none;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="logo">
            <img src="https://raw.githubusercontent.com/dgtlss/warden/refs/heads/main/public/warden-logo.png" alt="Logo">
        </div>
        <div class="title">
            Warden Audit Report
        </div>
        <div class="report-content">
            <p>Here is your warden audit report for {{ now()->format('F j, Y') }}.</p> 

            @foreach($report as $finding)
                <h3>{{ $finding['source'] }} Issue Found</h3>
                <table>
                    <tr>
                        <th>Package</th>
                        <td>{{ $finding['package'] }}</td>
                    </tr>
                    <tr>
                        <th>Title</th>
                        <td>{{ $finding['title'] }}</td>
                    </tr>
                    <tr>
                        <th>Severity</th>
                        <td>{{ $finding['severity'] }}</td>
                    </tr>
                    @if(isset($finding['cve']) && $finding['cve'] !== '-')
                    <tr>
                        <th>CVE</th>
                        <td><a href="https://www.cve.org/CVERecord?id={{ $finding['cve'] }}">{{ $finding['cve'] }}</a></td>
                    </tr>
                    @endif
                    @if(isset($finding['affected_versions']) && $finding['affected_versions'] !== '-')
                    <tr>
                        <th>Affected Versions</th>
                        <td>{{ $finding['affected_versions'] }}</td>
                    </tr>
                    @endif
                </table>
            @endforeach

            <footer>
                <span>This report was automatically generated by Warden.</span>
                <a href="https://github.com/dgtlss/warden">Warden on GitHub</a>
            </footer>
        </div>
    </div>
</body>
</html>