name: CI

on:
  push:
    branches: [ main, feature/upgrades ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.1, 8.2, 8.3]
        laravel: [9, 10, 11, 12]
        exclude:
          - laravel: 11
            php: 8.1
          - laravel: 12
            php: 8.1

    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Cache Composer dependencies
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php }}-laravel-${{ matrix.laravel }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-laravel-${{ matrix.laravel }}-composer-

      - name: Install Composer dependencies
        run: |
          composer require "laravel/framework:^${{ matrix.laravel }}.0" --no-update
          composer update --prefer-dist --no-progress --prefer-stable

      - name: Run tests
        run: vendor/bin/phpunit 